### ISSUE TITLE
Higher versions of javaparser cannot be used

### ISSUE THREAD

**Issue by Nihility981** [daanvdh/JavaDataFlowExample#1]
Just keep

`
<dependency>
			<groupId>com.github.daanvdh.javadataflow</groupId>
			<artifactId>JavaDataFlow</artifactId>
			<version>0.0.3</version>
		</dependency>
`
is work,if you use ` com.github.javaparser - javaparser-core - 3.24.0` is not work.

**Comment by daanvdh** [comment]
I believe this issue is for JavaDataFlow and not the example project right?

**Comment by Nihility981** [comment]
> I believe this issue is for JavaDataFlow and not the example project right?

yes

**Comment by Nihility981** [comment]
> I believe this issue is for JavaDataFlow and not the example project right?

Could you tell me your email address,I have an ongoing project to do something related. Maybe you can get inspiration from it

**Comment by daanvdh** [comment]
javaforger@gmail.com

**Comment by daanvdh** [comment]
I have some trouble deploying it to maven central, but if you check the project out on master you can use the 0.0.5 version.

**Comment by Nihility981** [comment]
> [javaforger@gmail.com](mailto:javaforger@gmail.com)
I have sent you an email. Please check it

**Comment by Nihility981** [comment]
> I have some trouble deploying it to maven central, but if you check the project out on master you can use the 0.0.5 version.
ok
