### ISSUE TITLE
Is there any way to present DFG as a picture?

### ISSUE THREAD

**Issue by ybsun0215** [daanvdh/JavaDataFlowExample#2]
I want to output DFG explicit as a graph, is there a encapsulated class to do this?

**Comment by daanvdh** [comment]
Currently there is no way to output the DFG as a picture. I made an effort to have the toString methods human readable, hopefully that helps. If someone makes an effort in converting the DFG to a picture I'll be more than happy to assist in getting it to work.

**Comment by daanvdh** [comment]
PS: This is the example project. For future issues, please add them to https://github.com/daanvdh/JavaDataFlow/issues/ instead.
